services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: smartdive-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: smartdive-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules